In [1]:
# 1. Create a scalar tensor with value 10 using tf.constant
#and print its value and data type.
import tensorflow as tf

x = tf.constant(10)

print("Tensor value:", x.numpy())
print("Tensor data type:", x.dtype)



Tensor value: 10
Tensor data type: <dtype: 'int32'>


In [2]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape
#and numpy value.


x = tf.constant([2, 4, 6, 8])

print("Tensor shape:", x.shape)
print("Tensor value:", x.numpy())


Tensor shape: (4,)
Tensor value: [2 4 6 8]


In [3]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant 
#and print its shape and dtype


x = tf.constant([[1, 2], [3, 4]])

print("Tensor shape:", x.shape)
print("Tensor data type:", x.dtype)


Tensor shape: (2, 2)
Tensor data type: <dtype: 'int32'>


In [4]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.


x = tf.Variable(5.0)

print("Current value:", x.numpy())


Current value: 5.0


In [5]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print
#the updated value.



x = tf.Variable(5.0)

x.assign(10.0)

print("Updated value:", x.numpy())


Updated value: 10.0


In [7]:

# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]]
#to add 1.0 to every element and print the result


x = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

y = tf.constant([[1.0, 1.0], [1.0, 1.0]])  
x.assign_add(y)

print("Updated value:\n", x.numpy())


Updated value:
 [[2. 3.]
 [4. 5.]]


In [6]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and 
#perform matrix multiplication using tf.matmul().



a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

c = tf.matmul(a, b)

print(c)


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [7]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print 
#its shape, dtype, and values.
t = tf.random.uniform(shape=(3, 3))

print("Shape:", t.shape)
print("Dtype:", t.dtype)
print("Values:\n", t)

Shape: (3, 3)
Dtype: <dtype: 'float32'>
Values:
 tf.Tensor(
[[0.98011553 0.4462428  0.7676295 ]
 [0.9395319  0.85756063 0.46102345]
 [0.27883267 0.31908512 0.63899314]], shape=(3, 3), dtype=float32)
